### ISSUE TITLE
Problem handling subdocuments using mongoose models coding style - caster undefined

### ISSUE THREAD

**Issue by asykes74** [Appsilon/styleguide#3]
@marekrogala I am trying to implement the approach outlined in your wiki, Creating Mongoose Models with Typescript and it seems that I have hit a roadblock.  

seat.ts:
    ```
export let SeatSchema: Schema = new Schema({
        travelerId: {type: Schema.Types.ObjectId, required: true},
        seatClass: {type: Schema.Types.String, minlength: 5, maxlength:10, required: true, enum: [“FirstClass”, “Coach”]},
    	row: {type: Schema.Types.Number, required: true},
    	section: {type: Schema.Types.Number, required: true},
        hasBoarded: {type: Schema.Types.Boolean, required: false}
    });
    ```

plane.ts:
    ```
export let PlaneSchema: Schema = new Schema({
    	manufacturer: {type: Schema.Types.String, required: true},
    	seatsChart: [SeatSchema],
    	routeId: [{type: Schema.Types.ObjectId, ref: ‘routes’, required: true}];
    ```

iseat.ts: 
    ```
export interface ISeat {
        travelerId: string,
        seatClass: string,
    	row: number,
    	section: number,
        hasBoarded: boolean
    }
    ```

iplane.ts:
    ```
export interface IPlane {
    	manufacturer: string,
    	seatsChart: Types.DocumentArray<ISeatModel>,
    	routeId: [string]
    }
    ```

iseatmodel.ts:
    ```
export interface ISeatModel extends ISeat, Subdocument {
    }
    ```
   

 
iplanemodel.ts:
    ```
export interface IPlaneModel extends IPlane, Document {
    }
    ```

planerepository.ts:
    ```
constructor(db) {
    	this._model: Model<IPlaneModel> = db.model<IPlaneModel>(“Plane”, PlaneSchema);
    }
	.
	.
	.
    addNewSeat(planeId: string, seat: ISeat) {
    	let plane: IPlaneModel = await this._model.findById(planeId);
    	let newSeat: ISeatModel = plane.SeatsChart.create(seatAttributes); //******** this is where error occurs, I even tried push and save which generates a different error about caster being undefined ***************
    	plane.seatsChart.push(newSeat);
    	let planeUpdated: IPlane = await plane.save();
    }
    ```

This is the error I keep receiving:
TypeError: Cannot read property 'casterConstructor' of undefined
    at Array.create (/node_modules/mongoose/lib/types/documentarray.js:236:35)
		.
		.
		.
		.
		.

Not sure what the issue could be at this point.  For some reason, the code is fine until it gets to the .create method.  As described above, I even tried to remove .create and replace with .push and then save the plane document but the error message switched to "Cannot read property 'Caster' of undefined".  1) What appears to be the source of my issue in the example demonstrated above?  2) Do you have any code scenarios to deal with handling embedded documents within an array (subdocuments)?

**Comment by marekrogala** [comment]
Hi, 

Mongoose and Typescript this is indeed someting we have used at some point. However, we haven't been using this combination since 2014. Given how fast the JavaScript related technologies evolve, I expect the approach we had used is no longer functional. We'll remove this Wiki page, thanks for pointing this out! This wiki is focused on code style guides that we follow at Appsilon, so that Wiki page does not really belong here. I suggest you try to figure this out based on current Mongoose documentation.

**Comment by asykes74** [comment]
The approach seemed really sound and I do believe alot of developers still use due to the number of references I see related to it online.  First, does your shop still use this approach?  With this approach in mind, how does your shop handle subdocuments?  You would have to be using subdocuments for something.  I think that additional information would be helpful to me and others who are trying this approach, which is an approach I definitely really like.  Definitely, reconsider taking it down.

**Comment by marekrogala** [comment]
No, we don't use it anymore. In fact, we don't use this set of technologies at the moment, so it simply does not apply. 

When you figure this out, would you consider writing an updated version of this article and publishing it somewhere? (can be a Medium post or even a Github Gist). We could then point to your article as an updated version.
